# -*- coding: utf-8 -*-
"""calculator.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x6nygOcgpmBnvuVLwLfL4K7Xu32yrKff
"""

import math
class Calculator:
  def add(self, a, b):
     return a+b
  def subtract(self, a, b):
    return a-b
def squareRoot(self, a):
   return math.sqrt(a)
def multiply(a, b):
   return a*b